[package]

name = "argparse"
description = "Powerful command-line argument parsing library"
license = "MIT"
readme = "README.rst"
keywords = ["command-line", "cli", "command", "argument"]
homepage = "http://github.com/tailhook/rust-argparse"
version = "0.2.0"
authors = ["paul@colomiets.name"]

